FROM python:3.11-slim

WORKDIR /app

COPY app /app/app

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    requests

EXPOSE 9000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "9000"]
